//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExHyperV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExHyperV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GPU.
        /// </summary>
        public static string addgpu {
            get {
                return ResourceManager.GetString("addgpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges have been obtained..
        /// </summary>
        public static string Admin1 {
            get {
                return ResourceManager.GetString("Admin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Administrator privileges. GPU Paravirtualization disabled..
        /// </summary>
        public static string Admin2 {
            get {
                return ResourceManager.GetString("Admin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has assigned to .
        /// </summary>
        public static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string appversion {
            get {
                return ResourceManager.GetString("appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string arch {
            get {
                return ResourceManager.GetString("arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignable devices.
        /// </summary>
        public static string Assignabledevices {
            get {
                return ResourceManager.GetString("Assignabledevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper allocating devices may cause system instability, please operate with caution!.
        /// </summary>
        public static string attentionwords {
            get {
                return ResourceManager.GetString("attentionwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile time.
        /// </summary>
        public static string buildtime {
            get {
                return ResourceManager.GetString("buildtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if launched with admin privileges....
        /// </summary>
        public static string checkadmin {
            get {
                return ResourceManager.GetString("checkadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if CPU virtualization is enabled....
        /// </summary>
        public static string checkcpuct {
            get {
                return ResourceManager.GetString("checkcpuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if HyperV is installed....
        /// </summary>
        public static string checkhyperv {
            get {
                return ResourceManager.GetString("checkhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string checksetting {
            get {
                return ResourceManager.GetString("checksetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check system version....
        /// </summary>
        public static string checksys {
            get {
                return ResourceManager.GetString("checksys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if it is a server version....
        /// </summary>
        public static string checkversion {
            get {
                return ResourceManager.GetString("checkversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please shut down the virtual machine first!.
        /// </summary>
        public static string Colsefirst {
            get {
                return ResourceManager.GetString("Colsefirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        public static string complicate {
            get {
                return ResourceManager.GetString("complicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility and Settings.
        /// </summary>
        public static string complisetting {
            get {
                return ResourceManager.GetString("complisetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable virtual machines to manage CPU cache....
        /// </summary>
        public static string cpucache {
            get {
                return ResourceManager.GetString("cpucache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Device Assignment.
        /// </summary>
        public static string DDA {
            get {
                return ResourceManager.GetString("DDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host system is not a server version, so Discrete Device Assignment cannot be used!.
        /// </summary>
        public static string ddaa {
            get {
                return ResourceManager.GetString("ddaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling device....
        /// </summary>
        public static string Disabledevice {
            get {
                return ResourceManager.GetString("Disabledevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , GPU virtualization feature has been disabled..
        /// </summary>
        public static string disablegpu {
            get {
                return ResourceManager.GetString("disablegpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable security policy (RequireSecureDeviceAssignment、RequireSupportedDeviceAssignment).
        /// </summary>
        public static string disablereg {
            get {
                return ResourceManager.GetString("disablereg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismounting devices....
        /// </summary>
        public static string Dismountdevice {
            get {
                return ResourceManager.GetString("Dismountdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during driver injection! Check if BitLocker is enabled on the system disk, or if there is no Windows directory?.
        /// </summary>
        public static string drivererror {
            get {
                return ResourceManager.GetString("drivererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Version.
        /// </summary>
        public static string driverversion {
            get {
                return ResourceManager.GetString("driverversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling device....
        /// </summary>
        public static string enabling {
            get {
                return ResourceManager.GetString("enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily use Hyper-V advanced features.
        /// </summary>
        public static string exhyperv {
            get {
                return ResourceManager.GetString("exhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the path of the device....
        /// </summary>
        public static string getpath {
            get {
                return ResourceManager.GetString("getpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Code.
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU virtualization has been enabled..
        /// </summary>
        public static string GPU1 {
            get {
                return ResourceManager.GetString("GPU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU virtualization is not enabled..
        /// </summary>
        public static string GPU2 {
            get {
                return ResourceManager.GetString("GPU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Partition.
        /// </summary>
        public static string gpupv {
            get {
                return ResourceManager.GetString("gpupv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU partition ID.
        /// </summary>
        public static string gpupvid {
            get {
                return ResourceManager.GetString("gpupvid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Path.
        /// </summary>
        public static string gpupvpath {
            get {
                return ResourceManager.GetString("gpupvpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Paravirtualization.
        /// </summary>
        public static string gpupvv {
            get {
                return ResourceManager.GetString("gpupvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Select.
        /// </summary>
        public static string GPUselect {
            get {
                return ResourceManager.GetString("GPUselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphicsmodel {
            get {
                return ResourceManager.GetString("Graphicsmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Card.
        /// </summary>
        public static string installedcard {
            get {
                return ResourceManager.GetString("installedcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceId.
        /// </summary>
        public static string Instanceid {
            get {
                return ResourceManager.GetString("Instanceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host system belongs to the server version..
        /// </summary>
        public static string Isserver {
            get {
                return ResourceManager.GetString("Isserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string kind {
            get {
                return ResourceManager.GetString("kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string manu {
            get {
                return ResourceManager.GetString("manu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memorycapacity {
            get {
                return ResourceManager.GetString("Memorycapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounting device....
        /// </summary>
        public static string mounting {
            get {
                return ResourceManager.GetString("mounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperV feature required.
        /// </summary>
        public static string needhyperv {
            get {
                return ResourceManager.GetString("needhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string notsupport {
            get {
                return ResourceManager.GetString("notsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed!.
        /// </summary>
        public static string operated {
            get {
                return ResourceManager.GetString("operated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Memory.
        /// </summary>
        public static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language will restart the application.
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Disassembled.
        /// </summary>
        public static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report or feedback.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing:  .
        /// </summary>
        public static string runerror {
            get {
                return ResourceManager.GetString("runerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host system is not a server version, and the virtual machine with the DDA device added will not be able to start!.
        /// </summary>
        public static string servererror {
            get {
                return ResourceManager.GetString("servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are being modified.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string soft {
            get {
                return ResourceManager.GetString("soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HyperV feature has been installed..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V feature is not installed..
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host Windows version is .
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the shutdown action of the virtual machine to force power off....
        /// </summary>
        public static string string5 {
            get {
                return ResourceManager.GetString("string5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between light/dark mode.
        /// </summary>
        public static string switchtheme {
            get {
                return ResourceManager.GetString("switchtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string systeminfo {
            get {
                return ResourceManager.GetString("systeminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , recommend the virtual machine version not be less than 19041..
        /// </summary>
        public static string v19041 {
            get {
                return ResourceManager.GetString("v19041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine List.
        /// </summary>
        public static string vmlist {
            get {
                return ResourceManager.GetString("vmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be interrupted, please wait.
        /// </summary>
        public static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
    }
}
