//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExHyperV.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExHyperV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string addgpu {
            get {
                return ResourceManager.GetString("addgpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Admin1 {
            get {
                return ResourceManager.GetString("Admin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Admin2 {
            get {
                return ResourceManager.GetString("Admin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string appversion {
            get {
                return ResourceManager.GetString("appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string arch {
            get {
                return ResourceManager.GetString("arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Assignabledevices {
            get {
                return ResourceManager.GetString("Assignabledevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string attentionwords {
            get {
                return ResourceManager.GetString("attentionwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string buildtime {
            get {
                return ResourceManager.GetString("buildtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string checkadmin {
            get {
                return ResourceManager.GetString("checkadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string checkcpuct {
            get {
                return ResourceManager.GetString("checkcpuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string checkhyperv {
            get {
                return ResourceManager.GetString("checkhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string checksetting {
            get {
                return ResourceManager.GetString("checksetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string checksys {
            get {
                return ResourceManager.GetString("checksys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Colsefirst {
            get {
                return ResourceManager.GetString("Colsefirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string complicate {
            get {
                return ResourceManager.GetString("complicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string complisetting {
            get {
                return ResourceManager.GetString("complisetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string cpucache {
            get {
                return ResourceManager.GetString("cpucache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string DDA {
            get {
                return ResourceManager.GetString("DDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Disabledevice {
            get {
                return ResourceManager.GetString("Disabledevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string disablegpu {
            get {
                return ResourceManager.GetString("disablegpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string disablereg {
            get {
                return ResourceManager.GetString("disablereg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Dismountdevice {
            get {
                return ResourceManager.GetString("Dismountdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string driverversion {
            get {
                return ResourceManager.GetString("driverversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string exhyperv {
            get {
                return ResourceManager.GetString("exhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string getpath {
            get {
                return ResourceManager.GetString("getpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string GPU1 {
            get {
                return ResourceManager.GetString("GPU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string GPU2 {
            get {
                return ResourceManager.GetString("GPU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string gpupv {
            get {
                return ResourceManager.GetString("gpupv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string gpupvid {
            get {
                return ResourceManager.GetString("gpupvid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string gpupvpath {
            get {
                return ResourceManager.GetString("gpupvpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string gpupvv {
            get {
                return ResourceManager.GetString("gpupvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string GPUselect {
            get {
                return ResourceManager.GetString("GPUselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Graphicsmodel {
            get {
                return ResourceManager.GetString("Graphicsmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string installedcard {
            get {
                return ResourceManager.GetString("installedcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Instanceid {
            get {
                return ResourceManager.GetString("Instanceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string kind {
            get {
                return ResourceManager.GetString("kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string manu {
            get {
                return ResourceManager.GetString("manu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Memorycapacity {
            get {
                return ResourceManager.GetString("Memorycapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string mounting {
            get {
                return ResourceManager.GetString("mounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string needhyperv {
            get {
                return ResourceManager.GetString("needhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string notsupport {
            get {
                return ResourceManager.GetString("notsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string operated {
            get {
                return ResourceManager.GetString("operated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string runerror {
            get {
                return ResourceManager.GetString("runerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string soft {
            get {
                return ResourceManager.GetString("soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string string5 {
            get {
                return ResourceManager.GetString("string5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string switchtheme {
            get {
                return ResourceManager.GetString("switchtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string systeminfo {
            get {
                return ResourceManager.GetString("systeminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string v19041 {
            get {
                return ResourceManager.GetString("v19041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nul 的本地化字符串。
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string vmlist {
            get {
                return ResourceManager.GetString("vmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
    }
}
