//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExHyperV.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExHyperV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add GPU 的本地化字符串。
        /// </summary>
        public static string addgpu {
            get {
                return ResourceManager.GetString("addgpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New External Switch 的本地化字符串。
        /// </summary>
        public static string AddSwitch_DefaultName_External {
            get {
                return ResourceManager.GetString("AddSwitch_DefaultName_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Virtual Switch 的本地化字符串。
        /// </summary>
        public static string AddSwitch_DefaultName_Generic {
            get {
                return ResourceManager.GetString("AddSwitch_DefaultName_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Internal Switch 的本地化字符串。
        /// </summary>
        public static string AddSwitch_DefaultName_Internal {
            get {
                return ResourceManager.GetString("AddSwitch_DefaultName_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New NAT Switch 的本地化字符串。
        /// </summary>
        public static string AddSwitch_DefaultName_NAT {
            get {
                return ResourceManager.GetString("AddSwitch_DefaultName_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available physical network adapters 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Placeholder_NoAdaptersAvailable {
            get {
                return ResourceManager.GetString("AddSwitch_Placeholder_NoAdaptersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a network adapter... 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Placeholder_SelectAdapter {
            get {
                return ResourceManager.GetString("AddSwitch_Placeholder_SelectAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An External or NAT switch must have a physical network adapter selected. 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Validation_AdapterRequiredForExternalOrNat {
            get {
                return ResourceManager.GetString("AddSwitch_Validation_AdapterRequiredForExternalOrNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Validation_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AddSwitch_Validation_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A switch named &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Validation_NameExists {
            get {
                return ResourceManager.GetString("AddSwitch_Validation_NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create an External or NAT switch because no physical network adapters are available. 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Validation_NoAdaptersForExternalOrNat {
            get {
                return ResourceManager.GetString("AddSwitch_Validation_NoAdaptersForExternalOrNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system allows only one user-created NAT network. 的本地化字符串。
        /// </summary>
        public static string AddSwitch_Validation_OnlyOneNatAllowed {
            get {
                return ResourceManager.GetString("AddSwitch_Validation_OnlyOneNatAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator privileges have been obtained. 的本地化字符串。
        /// </summary>
        public static string Admin1 {
            get {
                return ResourceManager.GetString("Admin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator privileges not obtained. All functions are disabled. 的本地化字符串。
        /// </summary>
        public static string Admin2 {
            get {
                return ResourceManager.GetString("Admin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  has assigned to  的本地化字符串。
        /// </summary>
        public static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error applying memory settings: {0} 的本地化字符串。
        /// </summary>
        public static string ApplyMemorySettingsFailed {
            get {
                return ResourceManager.GetString("ApplyMemorySettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string appversion {
            get {
                return ResourceManager.GetString("appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Architecture 的本地化字符串。
        /// </summary>
        public static string arch {
            get {
                return ResourceManager.GetString("arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignable devices 的本地化字符串。
        /// </summary>
        public static string Assignabledevices {
            get {
                return ResourceManager.GetString("Assignabledevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention 的本地化字符串。
        /// </summary>
        public static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Improperly assigning devices can cause system instability. Please proceed with caution. 的本地化字符串。
        /// </summary>
        public static string attentionwords {
            get {
                return ResourceManager.GetString("attentionwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bridge 的本地化字符串。
        /// </summary>
        public static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile time 的本地化字符串。
        /// </summary>
        public static string buildtime {
            get {
                return ResourceManager.GetString("buildtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capacity 的本地化字符串。
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if launched with admin privileges... 的本地化字符串。
        /// </summary>
        public static string checkadmin {
            get {
                return ResourceManager.GetString("checkadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if CPU virtualization is enabled... 的本地化字符串。
        /// </summary>
        public static string checkcpuct {
            get {
                return ResourceManager.GetString("checkcpuct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if HyperV is installed... 的本地化字符串。
        /// </summary>
        public static string checkhyperv {
            get {
                return ResourceManager.GetString("checkhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string checksetting {
            get {
                return ResourceManager.GetString("checksetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check system version... 的本地化字符串。
        /// </summary>
        public static string checksys {
            get {
                return ResourceManager.GetString("checksys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if it is a server version... 的本地化字符串。
        /// </summary>
        public static string checkversion {
            get {
                return ResourceManager.GetString("checkversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please shut down the virtual machine first! 的本地化字符串。
        /// </summary>
        public static string Colsefirst {
            get {
                return ResourceManager.GetString("Colsefirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compatibility 的本地化字符串。
        /// </summary>
        public static string complicate {
            get {
                return ResourceManager.GetString("complicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compatibility and Settings 的本地化字符串。
        /// </summary>
        public static string complisetting {
            get {
                return ResourceManager.GetString("complisetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configured Speed 的本地化字符串。
        /// </summary>
        public static string ConfiguredSpeed {
            get {
                return ResourceManager.GetString("ConfiguredSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable virtual machines to manage CPU cache... 的本地化字符串。
        /// </summary>
        public static string cpucache {
            get {
                return ResourceManager.GetString("cpucache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discrete Device Assignment 的本地化字符串。
        /// </summary>
        public static string DDA {
            get {
                return ResourceManager.GetString("DDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host system is not a server version, so Discrete Device Assignment cannot be used! 的本地化字符串。
        /// </summary>
        public static string ddaa {
            get {
                return ResourceManager.GetString("ddaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while checking MMIO space: {0} 的本地化字符串。
        /// </summary>
        public static string DdaPage_Error_CheckMmioGeneric {
            get {
                return ResourceManager.GetString("DdaPage_Error_CheckMmioGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during execution:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string DdaPage_Error_ExecutionGeneric {
            get {
                return ResourceManager.GetString("DdaPage_Error_ExecutionGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update MMIO space. 的本地化字符串。
        /// </summary>
        public static string DdaPage_Error_UpdateMmioFailed {
            get {
                return ResourceManager.GetString("DdaPage_Error_UpdateMmioFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performing device assignment, please wait... 的本地化字符串。
        /// </summary>
        public static string DdaPage_Status_AssigningDevice {
            get {
                return ResourceManager.GetString("DdaPage_Status_AssigningDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutting down virtual machine &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        public static string DdaPage_Status_ShuttingDownVm {
            get {
                return ResourceManager.GetString("DdaPage_Status_ShuttingDownVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMIO Space Too Small 的本地化字符串。
        /// </summary>
        public static string DdaPage_Title_MmioSpaceTooSmall {
            get {
                return ResourceManager.GetString("DdaPage_Title_MmioSpaceTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes the power mode to High Performance when the VM is under high load, and to Power Saver during low load. 的本地化字符串。
        /// </summary>
        public static string Description_HyperVAutoTurbo {
            get {
                return ResourceManager.GetString("Description_HyperVAutoTurbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyper-V VM Turbo Scheduler, created and managed by the ExhyperV application. 的本地化字符串。
        /// </summary>
        public static string Description_HyperVRfScheduler {
            get {
                return ResourceManager.GetString("Description_HyperVRfScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum memory the virtual machine can expand to. 的本地化字符串。
        /// </summary>
        public static string Description_MaximumRAM {
            get {
                return ResourceManager.GetString("Description_MaximumRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned = (100% + Buffer%) * Demand 的本地化字符串。
        /// </summary>
        public static string Description_MemoryBuffer {
            get {
                return ResourceManager.GetString("Description_MemoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The priority for obtaining memory when the host is low on memory. 的本地化字符串。
        /// </summary>
        public static string Description_MemoryWeight {
            get {
                return ResourceManager.GetString("Description_MemoryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The minimum memory the virtual machine can shrink to. 的本地化字符串。
        /// </summary>
        public static string Description_MinimumRAM {
            get {
                return ResourceManager.GetString("Description_MinimumRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies the initial amount of memory required to start this virtual machine. 的本地化字符串。
        /// </summary>
        public static string Description_StartupRAM {
            get {
                return ResourceManager.GetString("Description_StartupRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Failed 的本地化字符串。
        /// </summary>
        public static string Dialog_Title_OperationFailed {
            get {
                return ResourceManager.GetString("Dialog_Title_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait 的本地化字符串。
        /// </summary>
        public static string Dialog_Title_PleaseWait {
            get {
                return ResourceManager.GetString("Dialog_Title_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling device... 的本地化字符串。
        /// </summary>
        public static string Disabledevice {
            get {
                return ResourceManager.GetString("Disabledevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , GPU virtualization feature has been disabled. 的本地化字符串。
        /// </summary>
        public static string disablegpu {
            get {
                return ResourceManager.GetString("disablegpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable security policy 的本地化字符串。
        /// </summary>
        public static string disablereg {
            get {
                return ResourceManager.GetString("disablereg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismounting devices... 的本地化字符串。
        /// </summary>
        public static string Dismountdevice {
            get {
                return ResourceManager.GetString("Dismountdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host (Management OS) 的本地化字符串。
        /// </summary>
        public static string DisplayName_HostManagementOS {
            get {
                return ResourceManager.GetString("DisplayName_HostManagementOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver injection failed. Please check if BitLocker is enabled on the system drive or if the Windows directory is missing. 的本地化字符串。
        /// </summary>
        public static string drivererror {
            get {
                return ResourceManager.GetString("drivererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Version 的本地化字符串。
        /// </summary>
        public static string driverversion {
            get {
                return ResourceManager.GetString("driverversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Dynamic Memory 的本地化字符串。
        /// </summary>
        public static string EnableDynamicMemory {
            get {
                return ResourceManager.GetString("EnableDynamicMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling device... 的本地化字符串。
        /// </summary>
        public static string enabling {
            get {
                return ResourceManager.GetString("enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOMMU is not enabled in the BIOS. DDA and GPU-PV are unavailable. 的本地化字符串。
        /// </summary>
        public static string Error_BiosIommuDisabled {
            get {
                return ResourceManager.GetString("Error_BiosIommuDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to get the hard disk path for virtual machine &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string Error_CannotGetVmHardDiskPath {
            get {
                return ResourceManager.GetString("Error_CannotGetVmHardDiskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get virtual machine information. 的本地化字符串。
        /// </summary>
        public static string Error_CannotGetVmInfo {
            get {
                return ResourceManager.GetString("Error_CannotGetVmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to parse MMIO space properties. 的本地化字符串。
        /// </summary>
        public static string Error_CannotParseMmioSpace {
            get {
                return ResourceManager.GetString("Error_CannotParseMmioSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Conflict 的本地化字符串。
        /// </summary>
        public static string Error_ConfigurationConflict {
            get {
                return ResourceManager.GetString("Error_ConfigurationConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create switch &apos;{0}&apos;: {1} 的本地化字符串。
        /// </summary>
        public static string Error_CreateSwitchFailed {
            get {
                return ResourceManager.GetString("Error_CreateSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation Failed 的本地化字符串。
        /// </summary>
        public static string Error_CreationFailed {
            get {
                return ResourceManager.GetString("Error_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete switch &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string Error_DeleteSwitchFailed {
            get {
                return ResourceManager.GetString("Error_DeleteSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion Failed 的本地化字符串。
        /// </summary>
        public static string Error_DeletionFailed {
            get {
                return ResourceManager.GetString("Error_DeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to export local registry information. 的本地化字符串。
        /// </summary>
        public static string Error_ExportLocalRegistryInfoFailed {
            get {
                return ResourceManager.GetString("Error_ExportLocalRegistryInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A physical network adapter must be specified for an external switch. 的本地化字符串。
        /// </summary>
        public static string Error_ExternalSwitchRequiresPhysicalAdapter {
            get {
                return ResourceManager.GetString("Error_ExternalSwitchRequiresPhysicalAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to find the system partition in the mounted hard disk &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string Error_FailedToFindSystemPartition {
            get {
                return ResourceManager.GetString("Error_FailedToFindSystemPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to mount hard disk &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string Error_FailedToMountHardDisk {
            get {
                return ResourceManager.GetString("Error_FailedToMountHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A fatal error occurred: {0} 的本地化字符串。
        /// </summary>
        public static string Error_FatalError {
            get {
                return ResourceManager.GetString("Error_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        public static string Error_GenericFormat {
            get {
                return ResourceManager.GetString("Error_GenericFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get network information. Please ensure the program is run with administrator privileges and the Hyper-V module is installed. 的本地化字符串。
        /// </summary>
        public static string Error_GetNetworkInfoFailed {
            get {
                return ResourceManager.GetString("Error_GetNetworkInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load data: {0} 的本地化字符串。
        /// </summary>
        public static string Error_LoadDataFailed {
            get {
                return ResourceManager.GetString("Error_LoadDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load network information: {0} 的本地化字符串。
        /// </summary>
        public static string Error_LoadNetworkInfoFailed {
            get {
                return ResourceManager.GetString("Error_LoadNetworkInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: An exception occurred while processing the NVIDIA registry: {0} 的本地化字符串。
        /// </summary>
        public static string Error_NvidiaRegistryProcessingException {
            get {
                return ResourceManager.GetString("Error_NvidiaRegistryProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to load the virtual machine registry offline. Please ensure the program is run with administrator privileges. 的本地化字符串。
        /// </summary>
        public static string Error_OfflineLoadVmRegistryFailed {
            get {
                return ResourceManager.GetString("Error_OfflineLoadVmRegistryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed: Only one NAT network is allowed.
        ///
        ///The existing NAT switch is: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string Error_OnlyOneNatNetworkAllowed {
            get {
                return ResourceManager.GetString("Error_OnlyOneNatNetworkAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed: The physical network adapter &apos;{0}&apos; is already in use by the switch &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string Error_PhysicalAdapterInUse {
            get {
                return ResourceManager.GetString("Error_PhysicalAdapterInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Failed to remove the read-only attribute from the old driver folder: {0} 的本地化字符串。
        /// </summary>
        public static string Error_RemoveOldDriverFolderReadOnlyFailed {
            get {
                return ResourceManager.GetString("Error_RemoveOldDriverFolderReadOnlyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Robocopy failed to copy driver files, exit code: {0} 的本地化字符串。
        /// </summary>
        public static string Error_RobocopyDriverCopyFailed {
            get {
                return ResourceManager.GetString("Error_RobocopyDriverCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: An unexpected system exception occurred - {0} 的本地化字符串。
        /// </summary>
        public static string Error_UnexpectedSystemException {
            get {
                return ResourceManager.GetString("Error_UnexpectedSystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error 的本地化字符串。
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to unmount GPU. 的本地化字符串。
        /// </summary>
        public static string Error_UnmountGpuFailed {
            get {
                return ResourceManager.GetString("Error_UnmountGpuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update configuration for switch &apos;{0}&apos;: {1} 的本地化字符串。
        /// </summary>
        public static string Error_UpdateSwitchConfigFailed {
            get {
                return ResourceManager.GetString("Error_UpdateSwitchConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Easily use Hyper-V advanced features 的本地化字符串。
        /// </summary>
        public static string exhyperv {
            get {
                return ResourceManager.GetString("exhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External 的本地化字符串。
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the path of the device... 的本地化字符串。
        /// </summary>
        public static string getpath {
            get {
                return ResourceManager.GetString("getpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Unable to retrieve the state of the virtual machine &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string GetVmState_Error {
            get {
                return ResourceManager.GetString("GetVmState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Code 的本地化字符串。
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU virtualization has been enabled. 的本地化字符串。
        /// </summary>
        public static string GPU1 {
            get {
                return ResourceManager.GetString("GPU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU virtualization is not enabled. 的本地化字符串。
        /// </summary>
        public static string GPU2 {
            get {
                return ResourceManager.GetString("GPU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to mount GPU: {0} 的本地化字符串。
        /// </summary>
        public static string GpuPartition_Error_MountGpuFailed {
            get {
                return ResourceManager.GetString("GpuPartition_Error_MountGpuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Partition 的本地化字符串。
        /// </summary>
        public static string gpupv {
            get {
                return ResourceManager.GetString("gpupv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU partition ID 的本地化字符串。
        /// </summary>
        public static string gpupvid {
            get {
                return ResourceManager.GetString("gpupvid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Path 的本地化字符串。
        /// </summary>
        public static string gpupvpath {
            get {
                return ResourceManager.GetString("gpupvpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Paravirtualization 的本地化字符串。
        /// </summary>
        public static string gpupvv {
            get {
                return ResourceManager.GetString("gpupvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Select 的本地化字符串。
        /// </summary>
        public static string GPUselect {
            get {
                return ResourceManager.GetString("GPUselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics 的本地化字符串。
        /// </summary>
        public static string Graphicsmodel {
            get {
                return ResourceManager.GetString("Graphicsmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Connection 的本地化字符串。
        /// </summary>
        public static string Hostconnected {
            get {
                return ResourceManager.GetString("Hostconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyper-V Memory 的本地化字符串。
        /// </summary>
        public static string HyperVMemory {
            get {
                return ResourceManager.GetString("HyperVMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOMMU is enabled in the BIOS. 的本地化字符串。
        /// </summary>
        public static string Info_BiosIommuEnabled {
            get {
                return ResourceManager.GetString("Info_BiosIommuEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMIO space is sufficient. 的本地化字符串。
        /// </summary>
        public static string Info_MmioSpaceSufficient {
            get {
                return ResourceManager.GetString("Info_MmioSpaceSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Hyper-V virtual switches were found.
        ///
        ///Please ensure the Hyper-V feature is installed and running. 的本地化字符串。
        /// </summary>
        public static string Info_NoSwitchesFound {
            get {
                return ResourceManager.GetString("Info_NoSwitchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics Card 的本地化字符串。
        /// </summary>
        public static string installedcard {
            get {
                return ResourceManager.GetString("installedcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed Memory 的本地化字符串。
        /// </summary>
        public static string InstalledMemory {
            get {
                return ResourceManager.GetString("InstalledMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InstanceId 的本地化字符串。
        /// </summary>
        public static string Instanceid {
            get {
                return ResourceManager.GetString("Instanceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal 的本地化字符串。
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream 的本地化字符串。
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Upstream 的本地化字符串。
        /// </summary>
        public static string Isolate {
            get {
                return ResourceManager.GetString("Isolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host system belongs to the server version. 的本地化字符串。
        /// </summary>
        public static string Isserver {
            get {
                return ResourceManager.GetString("Isserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class 的本地化字符串。
        /// </summary>
        public static string kind {
            get {
                return ResourceManager.GetString("kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physical Adapter 的本地化字符串。
        /// </summary>
        public static string Label_PhysicalNetworkAdapter {
            get {
                return ResourceManager.GetString("Label_PhysicalNetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Name 的本地化字符串。
        /// </summary>
        public static string Label_SwitchName {
            get {
                return ResourceManager.GetString("Label_SwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load data: {0} 的本地化字符串。
        /// </summary>
        public static string LoadDataFailed {
            get {
                return ResourceManager.GetString("LoadDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer 的本地化字符串。
        /// </summary>
        public static string manu {
            get {
                return ResourceManager.GetString("manu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum RAM 的本地化字符串。
        /// </summary>
        public static string MaximumRAM {
            get {
                return ResourceManager.GetString("MaximumRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory 的本地化字符串。
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Buffer 的本地化字符串。
        /// </summary>
        public static string MemoryBuffer {
            get {
                return ResourceManager.GetString("MemoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory 的本地化字符串。
        /// </summary>
        public static string Memorycapacity {
            get {
                return ResourceManager.GetString("Memorycapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Group 的本地化字符串。
        /// </summary>
        public static string MemoryGroup {
            get {
                return ResourceManager.GetString("MemoryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Weight 的本地化字符串。
        /// </summary>
        public static string MemoryWeight {
            get {
                return ResourceManager.GetString("MemoryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum RAM 的本地化字符串。
        /// </summary>
        public static string MinimumRAM {
            get {
                return ResourceManager.GetString("MinimumRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum RAM cannot be greater than Maximum RAM. 的本地化字符串。
        /// </summary>
        public static string MinRamGreaterThanMaxRam {
            get {
                return ResourceManager.GetString("MinRamGreaterThanMaxRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mounting device... 的本地化字符串。
        /// </summary>
        public static string mounting {
            get {
                return ResourceManager.GetString("mounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NAT 的本地化字符串。
        /// </summary>
        public static string NAT {
            get {
                return ResourceManager.GetString("NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HyperV feature required 的本地化字符串。
        /// </summary>
        public static string needhyperv {
            get {
                return ResourceManager.GetString("needhyperv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Topology 的本地化字符串。
        /// </summary>
        public static string NetDraw {
            get {
                return ResourceManager.GetString("NetDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Mode 的本地化字符串。
        /// </summary>
        public static string NetMode {
            get {
                return ResourceManager.GetString("NetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported 的本地化字符串。
        /// </summary>
        public static string notsupport {
            get {
                return ResourceManager.GetString("notsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Upstream 的本地化字符串。
        /// </summary>
        public static string Noupstream {
            get {
                return ResourceManager.GetString("Noupstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed! 的本地化字符串。
        /// </summary>
        public static string operated {
            get {
                return ResourceManager.GetString("operated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Number 的本地化字符串。
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a network adapter... 的本地化字符串。
        /// </summary>
        public static string Placeholder_SelectNetworkAdapter {
            get {
                return ResourceManager.GetString("Placeholder_SelectNetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Memory 的本地化字符串。
        /// </summary>
        public static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rated Speed 的本地化字符串。
        /// </summary>
        public static string RatedSpeed {
            get {
                return ResourceManager.GetString("RatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the language will restart the application 的本地化字符串。
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #Dismounted 的本地化字符串。
        /// </summary>
        public static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report or feedback 的本地化字符串。
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error executing:   的本地化字符串。
        /// </summary>
        public static string runerror {
            get {
                return ResourceManager.GetString("runerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host system is not a server version, and the virtual machine with the DDA device added will not be able to start! 的本地化字符串。
        /// </summary>
        public static string servererror {
            get {
                return ResourceManager.GetString("servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings are being modified 的本地化字符串。
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App 的本地化字符串。
        /// </summary>
        public static string soft {
            get {
                return ResourceManager.GetString("soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup RAM 的本地化字符串。
        /// </summary>
        public static string StartupRAM {
            get {
                return ResourceManager.GetString("StartupRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup RAM cannot be less than Minimum RAM. 的本地化字符串。
        /// </summary>
        public static string StartupRamLessThanMinRam {
            get {
                return ResourceManager.GetString("StartupRamLessThanMinRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking BIOS setting: IOMMU... 的本地化字符串。
        /// </summary>
        public static string Status_CheckingBiosIommu {
            get {
                return ResourceManager.GetString("Status_CheckingBiosIommu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected to: {0} 的本地化字符串。
        /// </summary>
        public static string Status_ConnectedTo {
            get {
                return ResourceManager.GetString("Status_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unavailable 的本地化字符串。
        /// </summary>
        public static string Status_Unavailable {
            get {
                return ResourceManager.GetString("Status_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not connected to upstream network 的本地化字符串。
        /// </summary>
        public static string Status_UpstreamNotConnected {
            get {
                return ResourceManager.GetString("Status_UpstreamNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The HyperV feature has been installed. 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyper-V feature is not installed. 的本地化字符串。
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host Windows version is  的本地化字符串。
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify the shutdown action of the virtual machine to force power off... 的本地化字符串。
        /// </summary>
        public static string string5 {
            get {
                return ResourceManager.GetString("string5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported 的本地化字符串。
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Mode 的本地化字符串。
        /// </summary>
        public static string SwitchMode {
            get {
                return ResourceManager.GetString("SwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch between light/dark mode 的本地化字符串。
        /// </summary>
        public static string switchtheme {
            get {
                return ResourceManager.GetString("switchtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string systeminfo {
            get {
                return ResourceManager.GetString("systeminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Theme 的本地化字符串。
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Virtual Switch 的本地化字符串。
        /// </summary>
        public static string Title_AddVirtualSwitch {
            get {
                return ResourceManager.GetString("Title_AddVirtualSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyper-V Auto Turbo 的本地化字符串。
        /// </summary>
        public static string Title_HyperVAutoTurbo {
            get {
                return ResourceManager.GetString("Title_HyperVAutoTurbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Switch 的本地化字符串。
        /// </summary>
        public static string Title_VirtualSwitch {
            get {
                return ResourceManager.GetString("Title_VirtualSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall this virtual switch 的本地化字符串。
        /// </summary>
        public static string Uninstallswitch {
            get {
                return ResourceManager.GetString("Uninstallswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Failed 的本地化字符串。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , recommend the virtual machine version not be less than 19041. 的本地化字符串。
        /// </summary>
        public static string v19041 {
            get {
                return ResourceManager.GetString("v19041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Input 的本地化字符串。
        /// </summary>
        public static string Validation_InputInvalid {
            get {
                return ResourceManager.GetString("Validation_InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Switch List 的本地化字符串。
        /// </summary>
        public static string VirtualSwitchList {
            get {
                return ResourceManager.GetString("VirtualSwitchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Machine List 的本地化字符串。
        /// </summary>
        public static string vmlist {
            get {
                return ResourceManager.GetString("vmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Machine Memory 的本地化字符串。
        /// </summary>
        public static string VMMemory {
            get {
                return ResourceManager.GetString("VMMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string VMMemory_Status_Off {
            get {
                return ResourceManager.GetString("VMMemory_Status_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} MB (Demand) / {1} MB (Assigned) 的本地化字符串。
        /// </summary>
        public static string VMMemory_UsageFormat {
            get {
                return ResourceManager.GetString("VMMemory_UsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation cannot be interrupted, please wait 的本地化字符串。
        /// </summary>
        public static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a default switch and its settings cannot be modified. 的本地化字符串。
        /// </summary>
        public static string Warning_CannotModifyDefaultSwitch {
            get {
                return ResourceManager.GetString("Warning_CannotModifyDefaultSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MMIO space for virtual machine &apos;{0}&apos; is currently {1}GB, which is below the recommended 64GB.
        ///
        ///This may prevent the graphics card from acquiring enough memory space.
        ///
        ///Do you want to shut down the virtual machine and expand its MMIO space to 64GB? 的本地化字符串。
        /// </summary>
        public static string Warning_LowMmioSpace_ConfirmExpand {
            get {
                return ResourceManager.GetString("Warning_LowMmioSpace_ConfirmExpand", resourceCulture);
            }
        }
    }
}
